### PR TITLE
feat: .github/workflows: Add TS linter for frontend and backend

### LINKED ISSUE #2: Add Super-Linter workflow
Reference: https://github.com/super-linter/super-linter

### PR DESCRIPTION
**Pull request by gmacario**
Fix #2

See https://github.com/super-linter/super-linter

### CODE REVIEW

**Comment by gmacario** [comment]
The GitHub workflow is created in the feature branch, however it complains with a number of errors because of the codebase. 

@mariodedapolito would you like to give it a look? You can find them by clicking on the "Details" link just above.
Thanks!

**Comment by mariodedapolito** [comment]
Currently the code is not super-linter ready. I will make all the necessary changes for it pass the linter checks and then we can merge this PR. @gmacario @arol-varesi

**Comment by gmacario** [comment]
@mariodedapolito thanks for doing that. I will then reassign the PR to you. 

Please add the commits you need, when the checks are green you may then merge the PR

**Comment by mariodedapolito** [comment]
Adding superlinter for this type of repository (monorepo with FE + BE) is not ideal, as we can barely customize the linter behavior between FE (react) and BE. For this reason I have included customized linters (following best practices) for both FE and BE, and have triggered this linter + typescript compilation checks using Github Actions (similar to superlinter).

The code is fully lint-compatible, meaning it will pass both TS linting and also style linting for both FE and BE, but currently some features are broken due to these changes. I will take care to fix all features first (will take a bit of time) and then merge this PR.
@gmacario

**Comment by gmacario** [comment]
Thanks @mariodedapolito!

**Comment by gmacario** [comment]
> Adding superlinter for this type of repository (monorepo with FE + BE) is not ideal

I might agree for what concerns the JavaScript source files in folders react-client (FE) and express-server (BE).
However in my recent past I came to learn that Super-Linter is very smart on linting markdown, Dockerfiles, etc.

Therefore now that https://github.com/arol-polito/AROL-CLOUD/blob/main/.github/workflows/main.yml workflow is already in place I would not rule out the adoption of Super-Linter for the remaining files in this repository.

If/when I have some more holidays I will have a look and hopefully propose a PR 😄

**Pull request merged**
