### PR TITLE
[FIX] Fix a few bugs resulted from lint tickets modifications

### LINKED ISSUE #7: Fix bugs created from lint ticket modifications
In order to pass all lint checks, both FE and BE code were refactored. During this refactoring several bugs were introduced, mainly in the FE due to changes in the useEffect deps.

### PR DESCRIPTION
**Pull request by mariodeda97**
- Fix bugs created by eslint modifications
- Refactor whole dashboard functionality
- Dashboard optimizations
- Other bugs
- Code refactoring for increased readability

### CODE REVIEW

**Review by gmacario — COMMENTED** [review]
@mariodedapolito I had a quick look at the changes but I must admit it is a little bit overwhelming to review changes in 78 files!

```diff
@gmacario ➜ /workspaces/AROL-CLOUD (7-fix-bugs-created-from-lint-tickets-modifications) $ git diff origin/main..HEAD | diffstat
 b/express-server/src/entities/Dashboard.ts                                                                                                    |   89 
 b/express-server/src/repositories/DashboardRepository.ts                                                                                      |   12 
 b/express-server/src/repositories/MachineryRepository.ts                                                                                      |   31 
 b/express-server/src/services/MachineriesService.ts                                                                                           |    2 
 b/express-server/src/utils/SensorDataProcessor.ts                                                                                             |    1 
 b/react-client/package-lock.json                                                                                                              |56842 +++++++++++++++++++--------------------------------------------------------------------------------------------
 b/react-client/package.json                                                                                                                   |    7 
 b/react-client/src/dashboards/components/MachineryWithDashboardsCard.tsx                                                                      |   69 
 b/react-client/src/dashboards/pages/DashboardsPage.tsx                                                                                        |    4 
 b/react-client/src/documents/components/MachineryWithDocumentsCard.tsx                                                                        |   77 
 b/react-client/src/home/Home.tsx                                                                                                              |  192 
 b/react-client/src/layout/Navbar.tsx                                                                                                          |    4 
 b/react-client/src/layout/Sidebar.tsx                                                                                                         |   49 
 b/react-client/src/machineries-map/components/MapPanel.tsx                                                                                    |   28 
 b/react-client/src/machineries-map/components/NavigatorPanel.tsx                                                                              |   70 
 b/react-client/src/machineries/components/FilteringBar.tsx                                                                                    |   48 
 b/react-client/src/machineries/components/LogItem.tsx                                                                                         |   51 
 b/react-client/src/machineries/components/LogsControlBar.tsx                                                                                  |   31 
 b/react-client/src/machineries/components/LogsFilteringBar.tsx                                                                                |   23 
 b/react-client/src/machineries/components/MachineryCard.tsx                                                                                   |   33 
 b/react-client/src/machineries/components/SortingAndPaginationBar.tsx                                                                         |   74 
 b/react-client/src/machinery-users/components/MachineryModal.tsx                                                                              |   40 
 b/react-client/src/machinery/dashboard/components/DashboardPanel.tsx                                                                          |  933 -
 b/react-client/src/machinery/dashboard/components/dashboard-components/DashboardControlPanel.tsx                                              |  100 
 b/react-client/src/machinery/dashboard/components/dashboard-components/UnderlayDashboard.tsx                                                  |   50 
 b/react-client/src/machinery/dashboard/components/useDashboardPanelLogic.ts                                                                   |  499 
 b/react-client/src/machinery/dashboard/components/widget/MemoizedWidget.tsx                                                                   |   15 
 b/react-client/src/machinery/dashboard/components/widget/Widget.tsx                                                                           |  496 
 b/react-client/src/machinery/dashboard/components/widget/components/data-visualization/multi-value/MultiValueDataDisplay.tsx                  |   80 
 b/react-client/src/machinery/dashboard/components/widget/components/data-visualization/multi-value/components/MemoizedChart.tsx               |  395 
 b/react-client/src/machinery/dashboard/components/widget/components/data-visualization/multi-value/components/MemoizedChartControlPanel.tsx   |  237 
 b/react-client/src/machinery/dashboard/components/widget/components/data-visualization/multi-value/components/chart-components/Dot.tsx        |    8 
 b/react-client/src/machinery/dashboard/components/widget/components/data-visualization/multi-value/components/chart-components/PieTooltip.tsx |   25 
 b/react-client/src/machinery/dashboard/components/widget/components/data-visualization/multi-value/components/chart-components/Tooltip.tsx    |   77 
 b/react-client/src/machinery/dashboard/components/widget/components/data-visualization/multi-value/useMultiValueDataDisplayLogic.ts           |  605 +
 b/react-client/src/machinery/dashboard/components/widget/components/data-visualization/single-value/SingleValueDataDisplay.tsx                |  208 
 b/react-client/src/machinery/dashboard/components/widget/components/data-visualization/single-value/useSingleValueDataDisplayLogic.ts         |  166 
 b/react-client/src/machinery/dashboard/components/widget/components/modals/ChartFullscreenModal.tsx                                           |   72 
 b/react-client/src/machinery/dashboard/components/widget/components/modals/HistoryModal.tsx                                                   |  220 
 b/react-client/src/machinery/dashboard/components/widget/components/modals/LoadDashboardModal.tsx                                             |  192 
 b/react-client/src/machinery/dashboard/components/widget/components/modals/QuickNavigateModal.tsx                                             |  205 
 b/react-client/src/machinery/dashboard/components/widget/components/modals/SaveDashboardPrompt.tsx                                            |  118 
 b/react-client/src/machinery/dashboard/components/widget/components/modals/SensorsModal.tsx                                                   |  607 -
 b/react-client/src/machinery/dashboard/components/widget/components/modals/WidgetSettingsModal.tsx                                            |  629 +
 b/react-client/src/machinery/dashboard/components/widget/components/modals/useHistoryModalLogic.ts                                            |  132 
 b/react-client/src/machinery/dashboard/components/widget/components/widget-control-panel/WidgetControlPanel.tsx                               |  178 
 b/react-client/src/machinery/dashboard/components/widget/components/widget-control-panel/components/WidgetInfoPopover.tsx                     |   86 
 b/react-client/src/machinery/dashboard/components/widget/components/widget-control-panel/useWidgetControlPanelLogic.ts                        |   69 
 b/react-client/src/machinery/dashboard/components/widget/useWidgetLogic.ts                                                                    |  165 
 b/react-client/src/machinery/dashboard/interfaces/DataDisplaySize.ts                                                                          |    4 
 b/react-client/src/machinery/dashboard/interfaces/GridWidget.ts                                                                               |   34 
 b/react-client/src/machinery/dashboard/interfaces/PolarChartSensorData.ts                                                                     |    8 
 b/react-client/src/machinery/dashboard/interfaces/PolarChartSensorDataBucket.ts                                                               |    7 
 b/react-client/src/machinery/dashboard/interfaces/SaveDashboard.ts                                                                            |    9 
 b/react-client/src/machinery/dashboard/models/Dashboard.ts                                                                                    |   92 
 b/react-client/src/machinery/dashboard/utils.ts                                                                                               |  401 
 b/react-client/src/machinery/documents/components/DocumentViewer.tsx                                                                          |    4 
 b/react-client/src/machinery/documents/components/DocumentsPanel.tsx                                                                          |   88 
 b/react-client/src/machinery/documents/components/modals/DeleteFilesPrompt.tsx                                                                |   79 
 b/react-client/src/machinery/documents/components/modals/NewFolderPrompt.tsx                                                                  |  196 
 b/react-client/src/machinery/documents/components/modals/RenamePrompt.tsx                                                                     |   52 
 b/react-client/src/machinery/documents/components/modals/UploadFilesModal.tsx                                                                 |   59 
 b/react-client/src/machinery/machinery/MachineryPage.tsx                                                                                      |  139 
 b/react-client/src/machinery/machinery/components/HeadingPanel.tsx                                                                            |  340 
 b/react-client/src/machinery/machinery/components/LandingPanel.tsx                                                                            |   65 
 b/react-client/src/machinery/machinery/interfaces/LoadDashboardAction.ts                                                                      |    7 
 b/react-client/src/machinery/machinery/useMachineryPageLogic.ts                                                                               |  373 
 b/react-client/src/router/Router.tsx                                                                                                          |    2 
 b/react-client/src/users/components/PasswordResetModal.tsx                                                                                    |   13 
 b/react-client/src/users/components/UserAccountModal.tsx                                                                                      |   47 
 b/react-client/src/users/components/UserCard.tsx                                                                                              |   50 
 b/react-client/src/utils/AxiosExceptionHandler.ts                                                                                             |    3 
 b/react-client/src/utils/AxiosInterceptor.ts                                                                                                  |    4 
 react-client/src/machinery/dashboard/components/data-visualization/MultiValueDataDisplay.tsx                                                  | 1335 --
 react-client/src/machinery/dashboard/components/modals/ChartFullscreenModal.tsx                                                               |  102 
 react-client/src/machinery/dashboard/components/modals/WidgetSettingsModal.tsx                                                                |  587 -
 react-client/src/machinery/dashboard/components/widget/WidgetControlPanel.tsx                                                                 |  202 
 react-client/src/machinery/machinery/pages/MachineryPage.tsx                                                                                  |  309 
 78 files changed, 16441 insertions(+), 52514 deletions(-)
@gmacario ➜ /workspaces/AROL-CLOUD (7-fix-bugs-created-from-lint-tickets-modifications) $
```

**Comment by gmacario** [comment]
> I had a quick look at the changes but I must admit it is a little bit overwhelming to review changes in 78 files!

However I assume you already successfully run all the integration and e2e tests, therefore LGTM

**Review by gmacario — APPROVED** [review]

**Review by arol-varesi — CHANGES_REQUESTED** [review]
Tried project with Docker Desktop on my local machine and it seem working.

**Comment by gmacario** [comment]
@arol-varesi and @mariodedapolito

> Tried to run as Docker but result in some errors.
> Have you had the same problem?

I am testing the PR in a Codespace:

```bash
cd Docker
docker compose up --build
```

Result: TODO

**Review by gmacario — CHANGES_REQUESTED** [review]
@mariodedapolito please run "docker compose up --build" in a codespace and make sure the command executes successfully.

**Review by arol-varesi — DISMISSED** [review]

**Review by arol-varesi — CHANGES_REQUESTED** [review]
In Codespace I have the same error of @gmacario, so I tried to compile directly the client wich appears to give the error.

This is the result

```
@arol-varesi ➜ /workspaces/AROL-CLOUD/react-client (7-fix-bugs-created-from-lint-tickets-modifications) $ NODE_OPTIONS=--max_old_space_size=2048 npm run build

> react-client@0.1.0 build
> react-scripts build

Creating an optimized production build...
One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.

babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
go away.
  
The build failed because the process exited too early. Someone might have called `kill` or `killall`, or the system could be shutting down.
```

So it looks like there are some little problems on building the react-client.

**Comment by gmacario** [comment]
> So it looks like there are some little problems on building the react-client.

I wonder whether this is already tracked in #8

**Comment by mariodedapolito** [comment]
On it, I do agree with codespaces since on my machine everything is running as intended.

**Review by arol-varesi — COMMENTED** [review]
@mariodedapolito I tried this and for me is still not working.
Please precede your commit message with "[WIP]" until you consider your last commit OK to be checked.

**Comment by mariodedapolito** [comment]
@arol-varesi done, thank you.

Still investigating as the issue is now restricted only to Codespaces (tried both on mac and windows machine and it succeeds).

**Comment by gmacario** [comment]
> @arol-varesi done, thank you.
> 
> Still investigating as the issue is now restricted only to Codespaces (tried both on mac and windows machine and it succeeds). 

I would personally compare the results to the following programs on both failing and succeeding hosts to see whether we can find a pattern:

```shell
uname -a
lsb_release -a
node --version
npm --version
```

**Comment by mariodedapolito** [comment]
Thank you for the valuable tip @gmacario. Will report if I find a fix or find a pattern.

**Comment by mariodedapolito** [comment]
@gmacario @arol-varesi the docker problem we were experiencing was related to codespaces. After researching the issue my conclusion is that the process was terminating due to insufficient memory or due to codespaces-imposed timeouts.

In order to test the docker container, I added a github action that does just that, so this check is now part of the pipeline. I also replaced the `npm install` with `npm ci` which is meant to be used in automated environments. I also updated the node versions in both FE and BE docker containers. During these changes I also managed to fix the `--force` flag which was needed when `npm install` the project FE (react). Also upgraded `react-scripts` to v5.0.1 which includes much more modern SSL support.

Github action run: https://github.com/arol-polito/AROL-CLOUD/actions/runs/5993565075

**Review by arol-varesi — COMMENTED** [review]
@mariodedapolito I agree with the automation that tests the docker compose.

I tried again to do the docker compose locally before giving my approval. 
I do not know why now I have some problems on starting MongoDB (seem impossible to open the 57017 port). Probably is a problem on my laptop, but I ask you to try again in your local "Docker Desktop" just to be sure that all is still working. 

@mariodedapolito please let me know if for you is still working. Thank's

**Comment by mariodedapolito** [comment]
@arol-varesi tried on my mac and on windows and everything is working correctly for me. probably that port is already occupied on your machine and it fails because of that. this was also happening to some SDP project groups when we were using 27017 also for Docker, so that is why i changed it to 57017.  

image

**Comment by arol-varesi** [comment]
> @arol-varesi tried on my mac and on windows and everything is working correctly for me. probably that port is already occupied on your machine and it fails because of that. this was also happening to some SDP project groups when we were using 27017 also for Docker, so that is why i changed it to 57017.
> image

Very goo so I can approve this PR.

**Review by arol-varesi — APPROVED** [review]

**Comment by mariodedapolito** [comment]
Thank you @arol-varesi! Merging now to main.

**Pull request merged**
